name: Lint Workflow

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

      - name: Run Hadolint
        run: |
          docker run --rm -v $(pwd):/app -w /app hadolint/hadolint:latest hadolint --ignore DL3020 --ignore DL3006 Dockerfile

      - name: Run Super-Linter
        if: github.event_name == 'pull_request'
        uses: github/super-linter@v4